### ISSUE TITLE
Treat Both Comma (,) and Period (.) as Decimal Separators

### ISSUE THREAD

**Issue by JAremko** [JAremko/ArcherBC2#13]
We employ Java's NumberFormatter for handling formatted fields. It effectively manages real-time input validation as users type in values. Additionally, it processes the formatting of values according to specified precision (fraction digits), and efficiently eliminates spaces and other unwanted characters. This feature proves to be quite useful!

However, NumberFormatter utilizes the current locale settings to determine the handling of comma , and period . characters, treating one or the other as the decimal separator. Unfortunately, it lacks the configuration to accept both , and . as valid decimal separators.

Given the criticality of this part of the code to our project, and the high visibility of potential lag during user interactions, it is crucial that our solution remains highly performant  so I propose we consider reimplementing this feature at the Java level.

**Comment by o-murphy** [comment]
Try to replace it

```clojure
(defn str->double [s fraction-digits]
  (when-let [val (parse-input-str s fraction-digits)] (double val)))
```

with this

```clojure
(defn str->double [s fraction-digits]
  (when-let [val (parse-input-str (replace-commas-with-dots s) fraction-digits)]
    (double val)))

(defn replace-commas-with-dots [s]
  (clojure.string/replace s "," "."))
```

**Comment by JAremko** [comment]
@o-murphy   First we need to know the current locale rules then we can replace accordingly. Also it won't help with editing that shows red color when you add illegal character. 

I'll write a subclass for `DecimalFormat` that queries `DecimalFormatProperties.getDecimalSeparator()` and replaces  alternatives with it in overloaded `parse` method. Theoretically should work. Then I'll also have to plug it into extended `NumberFormatter ` used in `JFormattedTextField ` (this actually shows red border)

**Comment by o-murphy** [comment]
For our case we should not care about localisation, cause dot and comma should works independently of system locale, I can have uk-UA locale e.g. but I can change the keyboard layout when app already running, so if my layout is "UA" keyboard prints a comma, and if "EN" - a dot regardless of current system locale ("uk-UA" in our example)

**Comment by o-murphy** [comment]
Also by my experience, different systems get us current locale values in different formats (ua-ua, uk-UA, ua_ua, etc), so it's often so hard to catch all the system locale definition and handle them

**Comment by JAremko** [comment]
@o-murphy  Switching languages in app is actually switching locales so it's not a problem. I could've hardcode digital separator similarly to  https://github.com/JAremko/ArcherBC2/blob/24b2783d8e17497c31c6cd258ee6b8d3135db362/src/tvt/a7/profedit/config.clj#L22-L26

But it would be better to mate it work automatically with  custom java formatter.

**Comment by JAremko** [comment]
Should be fixed now.

**Comment by o-murphy** [comment]
I think that using of right-aligned float value inputs would be better, cause:
1. We would not need to print comma or dot directly in field (just numbers), app would insert separator automatically with accuracy specified.
2. Simplify conversions text to float and back
3. Simplify rounding values to specified accuracy
4. Supports better integration of units conversion in future (convertor might automaticaly set accuracy and min max values for a field)

Example bellow, don't think it just experience for mobile, on PC it's working too

https://github.com/JAremko/ArcherBC2/assets/73843436/d835f1e1-f1ba-4d19-a4ad-4f8c79c00427

**Comment by o-murphy** [comment]
It have to be kinda you enter numbers on POS terminal
