### ISSUE TITLE
[PROPOSAL] Visualisation of short-name-bot and short-name-top

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#14]
Add please visualisation of short-name-bot and short-name-top parameters as Icon in the app gui, cause It's not obvious what i need to fill there when profile builds  
![image](https://github.com/JAremko/ArcherBC2/assets/73843436/7c70deff-e7db-41ee-8dea-15dfbc29a71a)

**Comment by JAremko** [comment]
Added auto generation for `Top` and `Bottom`  in wizard. 
In the profile view we'll probably add icons.

Auto generation for `Top` will be improved.  For now it's simply shortened caliber.  We'll have [similar table](https://github.com/JAremko/ArcherBC2/blob/0f2f0d4bea855c2e9dfd6e09bbd13bf4ea988bff/src/tvt/a7/profedit/wizard.clj#L192-L251) for shortening known calibers into `Top`

**Comment by o-murphy** [comment]
> Додано автоматичне створення для `Top`та `Bottom` в майстрі. Можливо, у вікні профілю ми додамо піктограми або придумаємо кращу мітку.
> 
> Автоматична генерація для `Top`буде покращено. Поки що це просто укорочений калібр. У нас буде [аналогічна таблиця](https://github.com/JAremko/ArcherBC2/blob/0f2f0d4bea855c2e9dfd6e09bbd13bf4ea988bff/src/tvt/a7/profedit/wizard.clj#L192-L251) для вкорочення відомих калібрів`Top`

Firstly add a placeholders or popup hints (short name of caliber for profile icon) for example
Secondly I think you have to not remove autogeneration even after table would be added, for a top/bottom labels for calibers that would not predefine

**Comment by JAremko** [comment]
Done.
