### ISSUE TITLE
[PROPOSAL] Display a profile metadata of .a7p file on click it in files explorer

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#16]
Add please displaying a profile metadata of .a7p file on click it in files explorer
Show it in status bar or add widget to right side
It would be useful without opening the file for editing to see such data as a rifle / cartridge, etc
e.g. as on image below

![image](https://github.com/JAremko/ArcherBC2/assets/73843436/f1b3f798-49c8-4e31-b53a-dae9d3c46d05)

![image](https://github.com/JAremko/ArcherBC2/assets/73843436/74e922e4-6dbd-41d6-b044-7d96f9d040b4)

**Comment by JAremko** [comment]
We shave something like this now.  We'll see if the current info is sufficient.
