### ISSUE TITLE
[PROPOSAL] Propose file name on it's saving, Use system file dialogs

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#17]
Add proposition of file name on it's saving, base it on profile metadata, like "new_profile_<rifle_name>_<ammo_name>_<b-diameter>_<b-weight>.a7p"

It have to make searching the profile simple in files three

Also, maybe better use default system FileOpen/FileClose dialogs instead of framework's dialogs. They are more common, fammiliar and userfriendly that that's using now, a.g. below

![image](https://github.com/JAremko/ArcherBC2/assets/73843436/9034a9a8-562d-42a7-bd81-0f3c8b0f282c)

![image](https://github.com/JAremko/ArcherBC2/assets/73843436/18eb3fe1-39b3-42b3-aac9-c54a6b9f2f32)

**Comment by JAremko** [comment]
Done.
