### ISSUE TITLE
[PROPOSAL] Use app specific directory as default directory to saving profiles

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#18]
Use app specific directory as default directory to saving profiles instead of Documents, it have to simplify searching the files, cause wouldn't need to search it in many other files in Document dir 
Use `C:\Users\%USERPROFILE%\ArcherBC` or `C:\Users\%USERPROFILE%\Documents\ArcherBC for example`

**Comment by o-murphy** [comment]
App even doesn't remember last opened catalog, it'і annoying to search where i saved the file last time each time i open the app

**Comment by o-murphy** [comment]
So maybe is a good way to predefine default catalog in %User%/Documents/ArcherBC to store files

**Comment by JAremko** [comment]
Done.
