### ISSUE TITLE
[BUG] App freezes after closing file open/save dialogs

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#21]
After opening the file dialog to save file, whatever i do, saving file or clicking on cancel, app freezes for few seconds without indication of  some actions executing on background

**Comment by JAremko** [comment]
@o-murphy  Well, not sure if a bug.  But certainly we can add some kind of a spinner.  But yeah, we probably reload the same file on cancel so it also insures disk IO, file tree recreation and file validation.  I think after I rework the file tree it might go away and we won't need a spinner.   Currently the file tree does a lot of useless disk scanning and shows too much.

**Comment by o-murphy** [comment]
> @o-murphy Well, not sure if a bug. But certainly we can add some kind of a spinner. But yeah, we probably reload the same file on cancel so it also requires disk IO, file tree recreation and file validation. I think after I rework the file tree it might go away and we won't need a spinner. Currently the file tree does a lot of useless disk scanning and shows too much.

But if we click menu->reload action it not freezes the app, just on closing a file dialog

**Comment by JAremko** [comment]
That's actually can be the tree.  When you open the same file the tree can reuse cached nodes (JTree has internal cheche) 

If the problem persist after the tree rework I'll eyeball/profile to se what's going on.

**Comment by JAremko** [comment]
Also you can conform this by editing file on an empty thumb drive.  Building file tree for it should be cheap so the lag shouldn't be there.

**Comment by o-murphy** [comment]
> Also you can confirm this by editing file on an empty thumb drive. Building file tree for it should be cheap so the lag shouldn't be there.

I think tree not need to be full build for opened drive, better to build tree partial, to level of current selected dir, as is in many other apps, opening the dir has trigger loading of it's tree only

**Comment by JAremko** [comment]
Since I removed the tree it shouldn't be an issue now.   The new tree won't scan all the directories on disk.
