### ISSUE TITLE
[PROPOSAL] add shortcuts

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#22]
Add keyboard shortcuts to Menu actions (Ctrl+S, Ctrl+Shift+S for the saving, Ctrl+R for reload etc)

**Comment by JAremko** [comment]
![Screenshot_20230831_113518](https://github.com/JAremko/ArcherBC2/assets/1898905/3a42ca21-39fc-4843-85c7-faf967c981ef)

**Comment by o-murphy** [comment]
Good job

**Comment by JAremko** [comment]
fixed in c7ac7a291799900615511523bcecdf8f45b7a1dd
