### ISSUE TITLE
Not an obvious access to actions

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#23]
I think that main actions with file not have to be hiden in dropdown menu, when you working with many profiles in the same time.. ghosh..
![image](https://github.com/JAremko/ArcherBC2/assets/73843436/8faf6d4e-633f-4f80-9245-1c6ee9fb5cab)

**Comment by JAremko** [comment]
![image](https://github.com/JAremko/ArcherBC2/assets/1898905/0b018b0a-1be0-4600-a901-1ad14bea1673)
Looks ok
