### ISSUE TITLE
[PROPOSAL] Replace file tree to the side of app

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#24]
Replace file tree to the side of app, not as tab and make it always displayed on the screen (as is in Explorer or common IDE)
It would simplify work with 2 or more profiles in same time

**Comment by JAremko** [comment]
Profile names are long, so they will take up a lot of space and this will be a problem for users of devices with small screens. I'll probably add a pop-up button for creating separate window with the tree.  This way you would be able to move to an another screen.

**Comment by o-murphy** [comment]
>  Profile names are long, so they will take up a lot of space and this will be a problem for users of devices with small screens. I'll probably add a pop-up button for creating separate window with the tree.  This way you would be able to display it on a second screen.

You can display profile names partial, but on mouse over show full name in tooltip

**Comment by JAremko** [comment]
We have new file tree now.
