### ISSUE TITLE
[BUG] Two update processes in one time

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#28]
Able to run two update processes running in the same time if 2 app instances launched in the same time

Steps to reproduce:
1. Installed app version have to be not the latest version
2. execute 2 instances of the app. They both runnin the update dialog
3. Click the update button in both dialogs
4. App would be updated and wouldn't executing no more

Solution can be is preventing running 2 instances of the app in same time or prevent running update process twice if one is already running

**Comment by JAremko** [comment]
1.9.2 https://youtu.be/sqcLjcSloXs
