### ISSUE TITLE
[BUG] Old app version don't uninstalling fully

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#29]
If we reinstlling the app with installator it not uninstall previous version and after that sometimes the new version would not be able to open, it raises java error

**Comment by JAremko** [comment]
Added full clean-up https://github.com/JAremko/ArcherBC2/blob/fe5ef1fe77be780392f411a731efbf0b9b4b42d2/.github/workflows/install.iss#L58-L59
