### ISSUE TITLE
Add the gallery of the profiles

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#31]
1. Create a mountpoint for galery storage to the tree view (in AppData for example)
2. Add syncing it in the background
3. Make the profiles in gallery readonly
4. Add drag-n-drop to the tree view to simply adding profiles to the device/workdir

You can use a separated github repo or brunch in app repo to store and update the gallery and also for the versionong
After use GitHub REST API to fetch for the latest updates by the commit, and get the download links to the files or branch archive
In this way the update of the gallery will be available in just few http requests

My own gallery you can fing [here](https://github.com/o-murphy/a7p/tree/master/gallery)
Also you can get the updates by the release version from the [jsdelivr CDN](https://cdn.jsdelivr.net/gh/o-murphy/a7p/gallery/)
It is the profiles library that's already has the checked for the valid data profiles

**Comment by SVL101** [comment]
А навіщо профілі викладати у вільний доступ?

**Comment by o-murphy** [comment]
Для того що і прога в вільному доступі, щоб юзери займали менше часу на пошук даних, щоб могли самостійно налаштувати прилад, а не дзвонили по кожному новому патрону. в Applied ballistics наприклад все окрім кастомних дф відкрите
