### ISSUE TITLE
Merge screens of BC-data properties in profile creator

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#33]
Join this screens to one. It's too strange and useless to have a separate screen for each one parameter

![image](https://github.com/JAremko/ArcherBC2/assets/73843436/bbb5d746-7506-4030-a469-415440f65e3d)
![image](https://github.com/JAremko/ArcherBC2/assets/73843436/e117ec6c-e03f-4db5-8593-c552f8d340b6)

**Comment by JAremko** [comment]
Merged two of them (the last one is generated based on the choices in the previous ones so changing them would reset the last one + a lot of items of a different types on a single panel would be a bit overwhelming)

**Comment by o-murphy** [comment]
> Об’єднано два з них (останній генерується на основі вибору в попередніх, тому зміна їх призведе до скидання останнього + багато елементів різних типів на одній панелі було б трохи переважним)

> зміна їх призведе до скидання останнього
це не викликає проблеми під час редагування вже існуючого профілю (розмістити все це на одній сторінці)

> багато елементів різних типів
в майстрі створення профілю немає кастомних функцій, тож перевантаження не буде
