### ISSUE TITLE
Hotkey does not perform its function

### ISSUE THREAD

**Issue by BogdanWan** [JAremko/ArcherBC2#55]
When using a hotkey with the first press, the function is not performed. First of all, when a cell is selected, it deselects it, and the second click performs the required function.

**Comment by JAremko** [comment]
Need step-by-step instructions on how to reproduce.

**Comment by JAremko** [comment]
Ah ok I see. If  you edit value and then press save it won't work the first time 🤔

**Comment by o-murphy** [comment]
same think happens on copying a zeroing parameters

**Comment by JAremko** [comment]
@o-murphy  Try this version https://github.com/JAremko/ArcherBC2_testing/releases/tag/1.17.1

It should fix the "not triggering first time" issue.    In the DnD menu they aren't triggering because it doesn't have hotkeys at all (separate thingy).

**Comment by BogdanWan** [comment]
Збереження через ctrl+s у DnD не працює поки активне "меню перетягування",треба перемикатись з вікна на вікно.

**Comment by o-murphy** [comment]
> Збереження через ctrl+s у DnD не працює поки активне "меню перетягування",треба перемикатись з вікна на вікно.

@JAremko це треба пофіксити все таки

**Comment by JAremko** [comment]
@o-murphy  @BogdanWan  зробив у тестовій версії

**Comment by BogdanWan** [comment]
@JAremko все ок
