### ISSUE TITLE
Додати drag-n-drop до перегляду файлів

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#58]
`moved from gdocs`

> @JAremko: Мабуть, додам хоткей, який показуватиме драг-енд-дроп панель із двома таргетами (іконками). Якщо на один перетягнути - файл відкриється. Якщо на інший - пристілка імпортнется.

> @o-murphy: тільки драг н дроп має працювати при перетягуванні одного (вже пристріляного профіля) на будь який інший

> @JAremko: Через те нове меню драг-н-дропу (ctr-d) мае бути зручно (файли через меню теж відкриваются )

Питання стосувалось саме додавання профілів з каталогу archer_bc2_profiles до пристрою з допомогою ДнД, але ж коментар стосується переносу пристрілки, чи не так?

**Comment by JAremko** [comment]
То було про драг-дроп щоб не  використовувати незручний хоткей імпорту пристрілки з іншого файлу.
