### ISSUE TITLE
Add lapua custom drag function file import

### ISSUE THREAD

**Issue by tortorino** [JAremko/ArcherBC2#60]
Please add Lapua .drg files import. This is a text file with .drg extension. It contains all the info needed in the bullet section of the program. It will allow users to add CDF to their profile conveniently.
 This is an example of the file contents:
 CFM, .338 Lapua B557Lock Base 19.4g ( 300gr) - should be skipped
.0194 - weight in kg (convert and round it to grains) 
.00860 - diameter in meters (convert to inches)
0.0444 - length in meters (convert to inches)
> CFM, .338 Lapua B557Lock Base 19.4g ( 300gr), .0194, .00860, .0444, Radar Data
0.325	0.000
0.290	0.300
0.269	0.400
0.237	0.500
0.205	0.600
0.190	0.700
0.180	0.800
0.174	0.850
0.168	0.875
0.161	0.900
0.164	0.925
0.213	0.950
0.299	0.975
0.396	1.000
0.417	1.025
0.420	1.050
0.420	1.075
0.415	1.100
0.409	1.125
0.403	1.150
0.392	1.200
0.373	1.300
0.357	1.400
0.344	1.500
0.333	1.600
0.311	1.800
0.294	2.000
0.278	2.200
0.250	2.600
0.230	3.000
0.205	4.000
0.194	5.000

**Comment by tortorino** [comment]
[lapua_ballistics.tar.gz](https://github.com/JAremko/ArcherBC2/files/14083676/lapua_ballistics.tar.gz)

**Comment by JAremko** [comment]
Duplicate [19](https://github.com/JAremko/ArcherBC2/issues/19)
