### ISSUE TITLE
Виправлення стилю іконок налаштувань і властивостей вимкненого стану

### ISSUE THREAD

**Issue by o-murphy** [JAremko/ArcherBC2#63]
Частина іконок в вимкненому стані намальовані через 2 пікселі (С/М, REC), а нові іконки через 1 піксель (6X, LiPo)
- на дисплеї нові іконки виглядають світлішими за старі
- на фото нові іконки стають частково рожевими
- іконка PL в налаштуваннях світліша на дисплеї за інші, попри старий стиль (через 2 пікселі)
- через AV різницю в кольорі не помітно 

![Image](https://github.com/JAremko/ArcherBC2/assets/73843436/414225f8-5090-463d-b0b4-d507d79bfa09)
![Image](https://github.com/JAremko/ArcherBC2/assets/73843436/41a9a25a-2f52-4fff-ac03-86899267bf5f)

**Comment by JAremko** [comment]
https://youtu.be/69LuTnxa3z8 :thinking:

**Comment by o-murphy** [comment]
> https://youtu.be/69LuTnxa3z8 🤔

Не туди
